name: test
on:
    workflow_dispatch:
      inputs:
        runid:
           required: false
           type: string

env:
   RUNID: ${{github['run_id']}}
   GITHUB_ENV: ${{ toJSON(github) }}
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}ß
         

jobs: 
    Test:
        permissions: write-all
        runs-on: ubuntu-latest
        environment: DEV      
    
        steps:
            - name: Set the value
              id: step_one
              run: |
                echo "action_state=yellow" >> "$GITHUB_ENV"
                echo "runid=${{github['run_id']}}" >> "$GITHUB_ENV"

            - uses: actions/checkout@v3    
                
            - name: Use the value
              id: step_two
              run: |
                echo "${{ env.action_state }}" # This will output 'yellow'
                echo "${{env.runid}}"

            - name: Update environment file with 'run_id' value
              run: |
                echo "${{github['run_id']}}"  > file
                cat file

            - name: List directories
              run: |
                  ls -la      
            
            - name: Inputs runid (workflow call)
              if: ${{ inputs.runid }} != ''
              run: 'gh variable set RUN_ID < file'
              

            - name: Set runid variable 
              run: echo "${{vars.runid}}" 

            # - name: Get the run_id value
            #   run:  |
            #     echo "$GITHUB_RUN_ID"
            #     echo "workflow run_id: ${{github.run_id}}"
            #     echo "workflow run_id: ${{github['run_id']}}"  
            #     echo "workflow name: ${{github.workflow}}"
            #     echo "workflow name: ${{github['workflow']}}"
            #     echo "Name of the workflow: $GITHUB_WORKFLOW"

            # - name: Set color
            #   id: random-color-generator
            #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

            # - name: Get color
            #   run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"